export const arrData = [
    {
        createdAt: "2023-11-03T02:07:09.423Z",
        nickname: "Dr. Clint Christiansen",
        avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/36.jpg",
        content: "레알 이적 가즈아",
        writedTo: "손흥민",
        id: "1",
    },
    {
        createdAt: "2023-11-02T23:13:18.491Z",
        nickname: "Chad Graham",
        avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/298.jpg",
        content: "부상 당하지 말자",
        writedTo: "손흥민",
        id: "2",
    },
    {
        createdAt: "2023-11-02T11:25:37.026Z",
        nickname: "Tommy Abshire",
        avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/646.jpg",
        content: "제발 부상 회복하자...다이어 최악..",
        writedTo: "반더벤",
        id: "3",
    },
    {
        createdAt: "2023-11-02T16:06:34.150Z",
        nickname: "Max Mayert",
        avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/37.jpg",
        content: "패스 미쳤음 언능 회복하기를",
        writedTo: "매디슨",
        id: "4",
    },
    {
        createdAt: "2023-11-03T05:40:17.575Z",
        nickname: "Olga Christiansen",
        avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/720.jpg",
        content: "겁나 잘 막음",
        writedTo: "비카리오",
        id: "5",
    },
];
